### PR TITLE
added slack channels

### PR DESCRIPTION
**Pull request by pandapanda999**
Is this right?

### CODE REVIEW

**Comment by wabisabiyo** [comment]
???

**Comment by wabisabiyo** [comment]
what are you trying to achieve?

**Comment by wabisabiyo** [comment]
I understand what you're trying to add, but i think it's completely superfluous because that is already addressed in the documentation

**Comment by DustinWehr** [comment]
@yunlucao Item 3 of [Part 2](https://github.com/legalese/legalese.github.io/blob/master/doc/company.org#part-2-problem-specific--role-specific-onboarding), "Bias for public", goes into a lot more detail addressing the question you asked. In fact, in the FAQ subsection [FAQs about the organisation](https://github.com/legalese/legalese.github.io/blob/master/doc/company.org#faqs-about-the-organisation) just a little above the subsection you suggested adding to, it's question 1: 
> Why do I keep getting redirected to the group chat? / My main point of contact with Legalese is X, but when I try to talk to X about Legalese, X doesn’t seem to want to talk to me directly; instead, X tells me to talk on the mailing list, or the group chat. Why are they being so rude? Who do they think they are?

This makes me wonder whether you have read the entire document.

**Pull request closed without merging**
